version: '3.8'

services:
  db1:
    image: postgres:16
    container_name: msgcert-postgres-1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: msgcertdb
    ports:
      - "5433:5432"  # Host:Container
    volumes:
      - pgdata1:/var/lib/postgresql/data

  db2:
    image: postgres:16
    container_name: msgcert-postgres-2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: msgcertdb
    ports:
      - "5434:5432"
    volumes:
      - pgdata2:/var/lib/postgresql/data

  db3:
    image: postgres:16
    container_name: msgcert-postgres-3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: msgcertdb
    ports:
      - "5435:5432"
    volumes:
      - pgdata3:/var/lib/postgresql/data

  db4:
    image: postgres:16
    container_name: msgcert-postgres-4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: msgcertdb
    ports:
      - "5436:5432"
    volumes:
      - pgdata4:/var/lib/postgresql/data

  db5:
    image: postgres:16
    container_name: msgcert-postgres-5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: msgcertdb
    ports:
      - "5437:5432"
    volumes:
      - pgdata5:/var/lib/postgresql/data

  db6:
    image: postgres:16
    container_name: msgcert-postgres-6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: msgcertdb
    ports:
      - "5438:5432"
    volumes:
      - pgdata6:/var/lib/postgresql/data

volumes:
  pgdata1:
  pgdata2:
  pgdata3:
  pgdata4:
  pgdata5:
  pgdata6: